aws_account_id = "905418128143" // Replace it with your actual AWS account ID
isp_ip_address = "1.2.3.4/32"  // Replace it with the actual IP address of your ISP
ami = "ami-0bb84b8ffd87024d8" // Replace it the correct AMI that you're using at the time
az = "us-east-1a" // Change to region that you're working. I suggest use us-east-1 because it is the cheapist one
instance_type = "t2.micro" // For this lab t2.micro is more than enough to work, but if you want more feel free to change
key_name = "hoje" // Replace with the name of Key name that you've created
tg_ec2_1 = "10.200.1.33"
tg_ec2_2 = "10.200.1.34"
az_1a = "us-east-1a"
